apiVersion: v1
kind: Service
metadata:
  name: complaint-service
spec:
  selector:
    app: complaint-service
  ports:
    - port: 8001
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer
  externalName: complaint.service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaint-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complaint-service
  template:
    metadata:
      labels:
        app: complaint-service
    spec:
      containers:
        - name: complaint-service
          image: shyam/complaint_service
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "0.5"
              memory: "64Mi"
